<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SyouhinTable extends Model
{
    protected $table = 'syouhin';

    // データに挿入する値の定義
    public static $syouhin_table = [
        // SAUZA
        [
            'title_id' => 'sauza',
            'title_name' => 'SAUZA',
            'alt_name' => 'sauza_silver',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=753',
            'image' => 'sauza_silver.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Silver',
            'contents_alc' => '40%',
            'contents_dest' => 'サウザ蒸留所',
            'contents_nom' => '1102',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => '',
            'contents_review_flavor' => '',
            'contents_review_top' => '',
            'contents_review_after' => '爽やかな香りとキレのある王道テイスト',
        ],
        [
            'title_id' => 'sauza',
            'title_name' => 'SAUZA',
            'alt_name' => 'sauza_gold',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=754',
            'image' => 'sauza_gold.jpg',
            'aging_sort' => 'Gold',
            'aging' => 'Gold',
            'contents_alc' => '40%',
            'contents_dest' => 'サウザ蒸留所',
            'contents_nom' => '1102',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => '',
            'contents_review_flavor' => '',
            'contents_review_top' => '',
            'contents_review_after' => '爽快なキレの良さを残しつつ滑らかな風味',
        ],
        [
            'title_id' => 'sauza',
            'title_name' => 'SAUZA',
            'alt_name' => 'sauza_blue_silver',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=9796',
            'image' => 'sauza_blue_silver.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blue Silver',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'サウザ蒸留所',
            'contents_nom' => '1102',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => '',
            'contents_review_flavor' => '',
            'contents_review_top' => '',
            'contents_review_after' => '雑味が少ない爽快な香りが広がる',
        ],
        [
            'title_id' => 'sauza',
            'title_name' => 'SAUZA',
            'alt_name' => 'sauza_three_generations',
            'url' => 'https://sake.biccamera.com/bs/item/3285766/',
            'image' => 'sauza_three_generations.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Tres Generaciones Plata',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'サウザ蒸留所',
            'contents_nom' => '1102',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => '',
            'contents_review_flavor' => '',
            'contents_review_top' => '',
            'contents_review_after' => '爽やかながら芯のあるアガベ感',
        ],
            // Jose Cuervo
        [
            'title_id' => 'josecuervo',
            'title_name' => 'Jose Cuervo',
            'alt_name' => 'cuervo_silver',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=3084',
            'image' => 'cuervo_silver.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Especial Silver',
            'contents_alc' => '40%',
            'contents_dest' => 'クエルボ蒸留所',
            'contents_nom' => '1122',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => '',
            'contents_review_flavor' => '甘さ引き立つ上品漂う香り',
            'contents_review_top' => '',
            'contents_review_after' => '',
        ],
        [
            'title_id' => 'josecuervo',
            'title_name' => 'Jose Cuervo',
            'alt_name' => 'cuervo_reposado',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=738',
            'image' => 'cuervo_reposado.jpg',
            'aging_sort' => 'Reposado',
            'aging' => 'Especial Reposado',
            'contents_alc' => '40%',
            'contents_dest' => 'クエルボ蒸留所',
            'contents_nom' => '1122',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => '',
            'contents_review_flavor' => '',
            'contents_review_top' => '樽熟成による芯のある深みと滑らかさ',
            'contents_review_after' => '',
        ],
        [
            'title_id' => 'josecuervo',
            'title_name' => 'Jose Cuervo',
            'alt_name' => 'cuervo_traditional_silver',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=10315',
            'image' => 'cuervo_traditional_silver.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Traditional Silver',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'クエルボ蒸留所',
            'contents_nom' => '1122',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => '',
            'contents_review_flavor' => 'アガベの雑味が少ない甘味と上品な芳香',
            'contents_review_top' => '',
            'contents_review_after' => '',
        ],
        [
            'title_id' => 'josecuervo',
            'title_name' => 'Jose Cuervo',
            'alt_name' => '1800_silver',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=739',
            'image' => '1800_silver.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Silver',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'クエルボ蒸留所',
            'contents_nom' => '1122',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => '',
            'contents_review_flavor' => '',
            'contents_review_top' => '',
            'contents_review_after' => '柔和で甘い爽快感とスパイシーなキレの融合',
        ],
        [
            'title_id' => 'josecuervo',
            'title_name' => 'Jose Cuervo',
            'alt_name' => '1800_reposado',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=64',
            'image' => '1800_reposado.jpg',
            'aging_sort' => 'Reposado',
            'aging' => 'Reposado',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'クエルボ蒸留所',
            'contents_nom' => '1122',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => '',
            'contents_review_flavor' => '甘いすっきりとした香り',
            'contents_review_top' => '透き通った爽やかな甘味',
            'contents_review_after' => '滑らかな飲み心地',
        ],
        [
            'title_id' => 'josecuervo',
            'title_name' => 'Jose Cuervo',
            'alt_name' => 'cuervo_margarita',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=12865',
            'image' => 'cuervo_margarita.jpg',
            'aging_sort' => 'Cocktail',
            'aging' => 'Margarita',
            'contents_alc' => '18%/Liquor',
            'contents_dest' => 'クエルボ蒸留所',
            'contents_nom' => '1122',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => 'レポサドとライムのカクテル、マルガリータ',
            'contents_review_flavor' => 'さっぱりとした酸味が後に香るまろやかさ',
            'contents_review_top' => '甘みが強く、蜂蜜のようなとろみ',
            'contents_review_after' => '',
        ],
        // OLMECA
        [
            'title_id' => 'olmeca',
            'title_name' => 'OLMECA',
            'alt_name' => 'olmeca_blanco',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=747',
            'image' => 'olmeca_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blanco',
            'contents_alc' => '40%',
            'contents_dest' => 'ペルノ・リカール蒸留所',
            'contents_nom' => '1111',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'arandas',
            'contents_area' => 'アランダス地区',
            'contents_info' => '',
            'contents_review_flavor' => '',
            'contents_review_top' => '上品で甘さ控えめでドライなテイスト',
            'contents_review_after' => '',
        ],
        [
            'title_id' => 'olmeca',
            'title_name' => 'OLMECA',
            'alt_name' => 'olmeca_reposado',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=748',
            'image' => 'olmeca_reposado.jpg',
            'aging_sort' => 'Reposado',
            'aging' => 'Reposado',
            'contents_alc' => '40%',
            'contents_dest' => 'ペルノ・リカール蒸留所',
            'contents_nom' => '1111',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'arandas',
            'contents_area' => 'アランダス地区',
            'contents_info' => '',
            'contents_review_flavor' => '',
            'contents_review_top' => 'スパイス香るショット向きな大人テイスト',
            'contents_review_after' => '',
        ],
        // MARIACHI
        [
            'title_id' => 'mariachi',
            'title_name' => 'MARIACHI',
            'alt_name' => 'mariachi_silver',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=745',
            'image' => 'mariachi_silver.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Silver',
            'contents_alc' => '40%',
            'contents_dest' => 'ペルノ・リカール蒸留所',
            'contents_nom' => '1111',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'arandas',
            'contents_area' => 'アランダス地区',
            'contents_info' => '',
            'contents_review_flavor' => '',
            'contents_review_top' => '上品でまろやかな口当たり',
            'contents_review_after' => '',
        ],
        [
            'title_id' => 'mariachi',
            'title_name' => 'MARIACHI',
            'alt_name' => 'mariachi_gold',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=746',
            'image' => 'mariachi_gold.jpg',
            'aging_sort' => 'Gold',
            'aging' => 'Gold',
            'contents_alc' => '40%',
            'contents_dest' => 'ペルノ・リカール蒸留所',
            'contents_nom' => '1111',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'arandas',
            'contents_area' => 'アランダス地区',
            'contents_info' => '',
            'contents_review_flavor' => '',
            'contents_review_top' => 'スパイシーな香りとまろやかな甘さ',
            'contents_review_after' => '',
        ],
        // ALACRAN
        [
            'title_id' => 'alacran',
            'title_name' => 'ALACRAN',
            'alt_name' => 'alacran_blanco',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=14',
            'image' => 'alacran_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blanco',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'フィノス・デ・アガベ蒸留所',
            'contents_nom' => '1416',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => '',
            'contents_review_flavor' => 'サイダーのような爽やかな香り',
            'contents_review_top' => '甘い口当たり',
            'contents_review_after' => '',
        ],
        [
            'title_id' => 'alacran',
            'title_name' => 'ALACRAN',
            'alt_name' => 'alacran_crystal_anejo',
            'url' => 'https://wazawaza.jp/products/detail.php?product_id=601',
            'image' => 'alacran_crystal_anejo.jpg',
            'aging_sort' => 'Others',
            'aging' => 'Crystal Anejo',
            'contents_alc' => '35%/100%AGAVE',
            'contents_dest' => 'フィノス・デ・アガベ蒸留所',
            'contents_nom' => '1416',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => '熟成したアネホを独自に濾過を施し、透明に',
            'contents_review_flavor' => 'クリームソーダ風の爽やかな香り',
            'contents_review_top' => 'バニラと蜂蜜を思わすまろやかさ',
            'contents_review_after' => '滑らかな舌触りと酸味のある後味',
        ],
        // AHA TORO
        [
            'title_id' => 'ahatoro',
            'title_name' => 'AHA TORO',
            'alt_name' => 'ahatoro_blanco',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=15',
            'image' => 'ahatoro_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blanco',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'グルポ・テキレロ・デ・ロスアルトス蒸留所',
            'contents_nom' => '1548',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'arandas',
            'contents_area' => 'アランダス地区',
            'contents_info' => '',
            'contents_review_flavor' => '甘く優しい香り',
            'contents_review_top' => '',
            'contents_review_after' => 'キレのある苦み',
        ],
        [
            'title_id' => 'ahatoro',
            'title_name' => 'AHA TORO',
            'alt_name' => 'ahatoro_anejo',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=17',
            'image' => 'ahatoro_anejo.jpg',
            'aging_sort' => 'Anejo',
            'aging' => 'Anejo',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'グルポ・テキレロ・デ・ロスアルトス蒸留所',
            'contents_nom' => '1548',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'arandas',
            'contents_area' => 'アランダス地区',
            'contents_info' => '',
            'contents_review_flavor' => '',
            'contents_review_top' => '熟成しつつもあっさりとした飲み口',
            'contents_review_after' => '',
        ],
        // El Tesoro
        [
            'title_id' => 'eltesoro',
            'title_name' => 'El Tesoro',
            'alt_name' => 'eltesoro_anejo',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=173',
            'image' => 'eltesoro_anejo.jpg',
            'aging_sort' => 'ExtraAnejo',
            'aging' => 'Paradiso Anejo',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'ラ・アルテ－ニャ蒸留所',
            'contents_nom' => '1139',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'arandas',
            'contents_area' => 'アランダス地区',
            'contents_info' => 'コニャック樽で60ヶ月熟成',
            'contents_review_flavor' => '5年熟成の少し酸味ある香り',
            'contents_review_top' => '控えめな甘さ',
            'contents_review_after' => '',
        ],
        //Agavale
        [
            'title_id' => 'agavales',
            'title_name' => 'Agavales',
            'alt_name' => 'agavales_blanco',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=76',
            'image' => 'agavales_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blanco',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'デル・バジェ・デ・テキーラ蒸留所',
            'contents_nom' => '1438',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => '',
            'contents_review_flavor' => '',
            'contents_review_top' => '甘味が少なく辛みの感じるキレ',
            'contents_review_after' => '',
        ],
        // Ole
        [
            'title_id' => 'ole',
            'title_name' => 'Ole',
            'alt_name' => 'ole_silver',
            'url' => 'https://www.miraido-onlineshop.com/item/7-ole-tequila-40/',
            'image' => 'ole_silver.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Silver',
            'contents_alc' => '40%',
            'contents_dest' => 'ゴンザレス・ゴンザレス蒸留所',
            'contents_nom' => '1143',
            'contents_local_id' => 'centro',
            'contents_local' => 'ソナ・セントロ地方',
            'contents_area_id' => 'zapopan',
            'contents_area' => 'サポパン地区',
            'contents_info' => '',
            'contents_review_flavor' => '漂うスパイシーな香り',
            'contents_review_top' => 'キレもある飲みやすさ',
            'contents_review_after' => '',
        ],
        // Orendain
        [
            'title_id' => 'orendain',
            'title_name' => 'Orendain',
            'alt_name' => 'orendain_blanco',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=750',
            'image' => 'orendain_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blanco',
            'contents_alc' => '40%',
            'contents_dest' => 'オレンダイン蒸留所',
            'contents_nom' => '1110',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => '',
            'contents_review_flavor' => '深みのある爽やかな芳香',
            'contents_review_top' => '甘くなめらか',
            'contents_review_after' => '',
        ],
        // Camino
        [
            'title_id' => 'camino',
            'title_name' => 'Camino',
            'alt_name' => 'camino_blanco',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=743',
            'image' => 'camino_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blanco',
            'contents_alc' => '35%',
            'contents_dest' => 'カミノ・レアル蒸留所',
            'contents_nom' => '1487',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'arandas',
            'contents_area' => 'アランダス地区',
            'contents_info' => '',
            'contents_review_flavor' => 'フレッシュなアガベの優しい香り',
            'contents_review_top' => '滑らかな口当たりの飲みやすさ',
            'contents_review_after' => '',
        ],
        [
            'title_id' => 'camino',
            'title_name' => 'Camino',
            'alt_name' => '',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=744',
            'image' => 'camino_gold.jpg',
            'aging_sort' => 'Gold',
            'aging' => 'Gold',
            'contents_alc' => '40%',
            'contents_dest' => 'カミノ・レアル蒸留所',
            'contents_nom' => '1487',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'arandas',
            'contents_area' => 'アランダス地区',
            'contents_info' => '',
            'contents_review_flavor' => '滑らかな発酵の香り',
            'contents_review_top' => '豊かな甘さ',
            'contents_review_after' => '',
        ],
        // EL CHARRO
        [
            'title_id' => 'elcharro',
            'title_name' => 'EL CHARRO',
            'alt_name' => 'elcharro_silver',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=234',
            'image' => 'elcharro_silver.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Silver',
            'contents_alc' => '38%',
            'contents_dest' => 'カンパニャ・テキレラ・デ・アランダス蒸留所',
            'contents_nom' => '1460',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'arandas',
            'contents_area' => 'アランダス地区',
            'contents_info' => '',
            'contents_review_flavor' => 'スッキリと鼻に抜ける香り',
            'contents_review_top' => '滑らかな口当たり',
            'contents_review_after' => '',
        ],
        //  HERRADURA
        [
            'title_id' => 'herradura',
            'title_name' => 'HERRADURA',
            'alt_name' => 'herradura_plata',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=89',
            'image' => 'herradura_plata.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Plata',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'カーサ・エラドゥーラ蒸留所',
            'contents_nom' => '1119',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'amatitan',
            'contents_area' => 'アマティタン地区',
            'contents_info' => '',
            'contents_review_flavor' => '樽の発酵香とほのかなスパイシーさ',
            'contents_review_top' => '程よい甘さ',
            'contents_review_after' => '',
        ],
        // CORRALEJO
        [
            'title_id' => 'corralejo',
            'title_name' => 'CORRALEJO',
            'alt_name' => 'corralejo_anejo',
            'url' => 'https://www.premium-tequila.jp/products/detail.php?product_id=116',
            'image' => 'corralejo_anejo.jpg',
            'aging_sort' => 'Anejo',
            'aging' => 'Anejo',
            'contents_alc' => '38%/100%AGAVE',
            'contents_dest' => 'コラレホ蒸留所',
            'contents_nom' => '1368',
            'contents_local_id' => 'others',
            'contents_local' => 'グアナファト州',
            'contents_area_id' => 'penjamo',
            'contents_area' => 'ペンハモ地区',
            'contents_info' => 'テネシーウィスキー樽で1年熟成',
            'contents_review_flavor' => '熟成したシナモンのような深い香り',
            'contents_review_top' => 'バニラ引き立つ甘み',
            'contents_review_after' => '',
        ],
        // CAZADRES
        [
            'title_id' => 'cazadores',
            'title_name' => 'CAZADRES',
            'alt_name' => 'cazadores_blanco',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=61',
            'image' => 'cazadores_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blanco',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'カサドレス蒸留所',
            'contents_nom' => '1487',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'arandas',
            'contents_area' => 'アランダス地区',
            'contents_info' => '',
            'contents_review_flavor' => '上品でややスパイシーなハーブ香',
            'contents_review_top' => '滑らかな舌触り',
            'contents_review_after' => '',
        ],
        [
            'title_id' => 'cazadores',
            'title_name' => 'CAZADRES',
            'alt_name' => 'cazadores_anejo',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=63',
            'image' => 'cazadores_anejo.jpg',
            'aging_sort' => 'Anejo',
            'aging' => 'Anejo',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'カサドレス蒸留所',
            'contents_nom' => '1487',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'arandas',
            'contents_area' => 'アランダス地区',
            'contents_info' => 'アメリカンオークの新樽で18ヶ月熟成',
            'contents_review_flavor' => '薫るアガベの爽やかさ',
            'contents_review_top' => 'バニラのような熟成したコク',
            'contents_review_after' => '',
        ],
        // PORFIDIO
        [
            'title_id' => 'porfidio',
            'title_name' => 'PORFIDIO',
            'alt_name' => 'porfidio_silver',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=96',
            'image' => 'porfidio_silver.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Silver',
            'contents_alc' => '39.5%/100%AGAVE',
            'contents_dest' => 'インモビリアリア・マスト蒸留所',
            'contents_nom' => '1462',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'lasjuntas',
            'contents_area' => 'ラス・フンタス地区',
            'contents_info' => '厳密にはテキーラではない',
            'contents_review_flavor' => '複雑ながらすっきりとした芳醇な香り',
            'contents_review_top' => '丸みのある爽やかな飲み口',
            'contents_review_after' => '',
        ],
        // CASA DE LUNA
        [
            'title_id' => 'casadeluna',
            'title_name' => 'CASA DE LUNA',
            'alt_name' => 'casadeluna_blanco',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=4',
            'image' => 'casadeluna_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blanco',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'ファナカトラン蒸留所',
            'contents_nom' => '1551',
            'contents_local_id' => 'centro',
            'contents_local' => 'ソナ・セントロ地方',
            'contents_area_id' => 'juanakatlan',
            'contents_area' => 'ファナカトラン地区',
            'contents_info' => '',
            'contents_review_flavor' => '優しく鼻通る香り',
            'contents_review_top' => '滑らかな舌触り',
            'contents_review_after' => '少しのアルコール感',
        ],
        // TRES REYES
        [
            'title_id' => 'tresreyes',
            'title_name' => 'TRES REYES',
            'alt_name' => 'tresreyes_silver',
            'url' => 'https://www.miraido-onlineshop.com/item/7-tres-reyes-s/',
            'image' => 'tresreyes_silver.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Silver',
            'contents_alc' => '38%',
            'contents_dest' => 'カンパニャ・テキレラ・デ・アランダス蒸留所',
            'contents_nom' => '1460',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'arandas',
            'contents_area' => 'アランダス地区',
            'contents_info' => '',
            'contents_review_flavor' => '',
            'contents_review_top' => 'ビターな口当たり',
            'contents_review_after' => '甘みのある後味',
        ],
        // el jimador
        [
            'title_id' => 'eljimador',
            'title_name' => 'el jimador',
            'alt_name' => 'eljimador_blanco',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=101',
            'image' => 'eljimador_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blanco',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'カーサ・エラドゥーラ蒸留所',
            'contents_nom' => '1119',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'amatitan',
            'contents_area' => 'アマティタン地区',
            'contents_info' => '',
            'contents_review_flavor' => 'サイダーのような爽やかな香り',
            'contents_review_top' => 'ほんのりスパイシー',
            'contents_review_after' => '',
        ],
        // DonJurio
        [
            'title_id' => 'donjurio',
            'title_name' => 'DonJurio',
            'alt_name' => 'donjurio_blanco',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=14797',
            'image' => 'donjurio_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blanco',
            'contents_alc' => '38%/100%AGAVE',
            'contents_dest' => 'ドン・フリオ蒸留所',
            'contents_nom' => '1449',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'atotonirco',
            'contents_area' => 'アトトニルコ地区',
            'contents_info' => '',
            'contents_review_flavor' => '澄み渡ったまろやかな香り',
            'contents_review_top' => '適度な甘味',
            'contents_review_after' => '',
        ],
        [
            'title_id' => 'donjurio',
            'title_name' => 'DonJurio',
            'alt_name' => 'donjurio_anejo',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=68',
            'image' => 'donjurio_anejo.jpg',
            'aging_sort' => 'Anejo',
            'aging' => 'Anejo',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'ドン・フリオ蒸留所',
            'contents_nom' => '1449',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'atotonirco',
            'contents_area' => 'アトトニルコ地区',
            'contents_info' => 'アメリカンオーク樽で18ヶ月熟成',
            'contents_review_flavor' => 'コーヒー、バニラのようなまろやかなコクの熟成',
            'contents_review_top' => '蜂蜜に適度な酸味を感じる甘み',
            'contents_review_after' => '',
        ],
        // Casa Noble
        [
            'title_id' => 'casanoble',
            'title_name' => 'Casa Noble',
            'alt_name' => 'casanoble_blanco',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=72',
            'image' => 'casanoble_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Crystal Blanco',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'ラ・コフラディア蒸留所',
            'contents_nom' => '1137',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => '',
            'contents_review_flavor' => '爽やかなアガベの甘味香',
            'contents_review_top' => '滑らかな口当たり',
            'contents_review_after' => 'ほんのりシトラスの発酵感',
        ],
        [
            'title_id' => 'casanoble',
            'title_name' => 'Casa Noble',
            'alt_name' => 'casanoble_reposado',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=73',
            'image' => 'casanoble_reposado.jpg',
            'aging_sort' => 'Reposado',
            'aging' => 'Reposado',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'ラ・コフラディア蒸留所',
            'contents_nom' => '1137',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => 'フレンチオーク樽364日熟成',
            'contents_review_flavor' => '後から香るアガベ感',
            'contents_review_top' => 'カカオ香る甘み',
            'contents_review_after' => 'シトラスな後味',
        ],
        [
            'title_id' => 'casanoble',
            'title_name' => 'Casa Noble',
            'alt_name' => 'casanoble_anejo',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=74',
            'image' => 'casanoble_anejo.jpg',
            'aging_sort' => 'Anejo',
            'aging' => 'Anejo',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'ラ・コフラディア蒸留所',
            'contents_nom' => '1137',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => 'フレンチオークの新樽で24ヶ月熟成',
            'contents_review_flavor' => '芳醇で濃厚なカカオ香',
            'contents_review_top' => 'チョコのような甘味',
            'contents_review_after' => '',
        ],
        // KAH
        [
            'title_id' => 'kah',
            'title_name' => 'KAH',
            'alt_name' => 'kah_anejo',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=171',
            'image' => 'kah_anejo.jpg',
            'aging_sort' => 'Anejo',
            'aging' => 'Anejo',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'テキーラス・フィノス蒸留所',
            'contents_nom' => '1472',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => 'アメリカンオーク樽で2年の熟成',
            'contents_review_flavor' => '繊細でやさしい香り',
            'contents_review_top' => 'シトラスでほのかな甘み',
            'contents_review_after' => '',
        ],
        // PATRON
        [
            'title_id' => 'patron',
            'title_name' => 'PATRON',
            'alt_name' => 'patron_silver',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=58',
            'image' => 'patron_silver.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Silver',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'パトロン蒸留所',
            'contents_nom' => '1492',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'atotonirco',
            'contents_area' => 'アトトニルコ地区',
            'contents_info' => '',
            'contents_review_flavor' => '果実の複雑なシトラスとアガベ感じる香り',
            'contents_review_top' => 'ほのかなスパイス感とスムースな口当たり',
            'contents_review_after' => '蜂蜜のような甘み後味',
        ],
        [
            'title_id' => 'patron',
            'title_name' => 'PATRON',
            'alt_name' => 'patron_reposado',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=59',
            'image' => 'patron_reposado.jpg',
            'aging_sort' => 'Reposado',
            'aging' => 'Reposado',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'パトロン蒸留所',
            'contents_nom' => '1492',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'atotonirco',
            'contents_area' => 'アトトニルコ地区',
            'contents_info' => 'アメリカンオーク樽で6ヶ月熟成ブレンド',
            'contents_review_flavor' => 'シトラスで爽やかな香',
            'contents_review_top' => 'スパイス混ざる複雑なキレのある味',
            'contents_review_after' => '蜂蜜のような甘い樽の残り香',
        ],
        [
            'title_id' => 'patron',
            'title_name' => 'PATRON',
            'alt_name' => 'patron_anejo',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=60',
            'image' => 'patron_anejo.jpg',
            'aging_sort' => 'Anejo',
            'aging' => 'Anejo',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'パトロン蒸留所',
            'contents_nom' => '1492',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'atotonirco',
            'contents_area' => 'アトトニルコ地区',
            'contents_info' => 'アメリカン/フレンチオーク樽で12ヶ月熟成ブレンド',
            'contents_review_flavor' => 'シトラスでまろやかな香',
            'contents_review_top' => '複雑なスパイスと丸みを帯びた味',
            'contents_review_after' => 'バニラのような深みのある甘みと樽香',
        ],
        // La Tilica
        [
            'title_id' => 'latilica',
            'title_name' => 'La Tilica',
            'alt_name' => 'latilica_blanco',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=9500',
            'image' => 'latilica_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blanco',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'ファナカトラン蒸留所',
            'contents_nom' => '1551',
            'contents_local_id' => 'centro',
            'contents_local' => 'ソナ・セントロ地方',
            'contents_area_id' => 'juanakatlan',
            'contents_area' => 'ファナカトラン地区',
            'contents_info' => '',
            'contents_review_flavor' => '',
            'contents_review_top' => '芯のあるコクと苦みと硬質な舌触り',
            'contents_review_after' => '',
        ],
        // MUCHA LIGA
        [
            'title_id' => 'muchaliga',
            'title_name' => 'MUCHA LIGA',
            'alt_name' => 'muchaliga_blanco',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=200',
            'image' => 'muchaliga_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blanco(ブラーヴォ)',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'ファナカトラン蒸留所',
            'contents_nom' => '1551',
            'contents_local_id' => 'centro',
            'contents_local' => 'ソナ・セントロ地方',
            'contents_area_id' => 'juanakatlan',
            'contents_area' => 'ファナカトラン地区',
            'contents_info' => '',
            'contents_review_flavor' => 'しっかりとしたアガベの香り',
            'contents_review_top' => 'マイルドでスムースな口当たり',
            'contents_review_after' => 'シンプルにほのかな甘み',
        ],
        [
            'title_id' => 'muchaliga',
            'title_name' => 'MUCHA LIGA',
            'alt_name' => 'muchaliga_reposado',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=201',
            'image' => 'muchaliga_reposado.jpg',
            'aging_sort' => 'Reposado',
            'aging' => 'Reposado(カニバル)',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'ファナカトラン蒸留所',
            'contents_nom' => '1551',
            'contents_local_id' => 'centro',
            'contents_local' => 'ソナ・セントロ地方',
            'contents_area_id' => 'juanakatlan',
            'contents_area' => 'ファナカトラン地区',
            'contents_info' => 'バーボン樽で3ヶ月熟成',
            'contents_review_flavor' => '甘いカカオ樽香',
            'contents_review_top' => 'すっきりな酸味',
            'contents_review_after' => 'ほのかにスパイシーな後味',
        ],
        [
            'title_id' => 'muchaliga',
            'title_name' => 'MUCHA LIGA',
            'alt_name' => 'muchaliga_anejo',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=202',
            'image' => 'muchaliga_anejo.jpg',
            'aging_sort' => 'Anejo',
            'aging' => 'Anejo(インヴィクト)',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'ファナカトラン蒸留所',
            'contents_nom' => '1551',
            'contents_local_id' => 'centro',
            'contents_local' => 'ソナ・セントロ地方',
            'contents_area_id' => 'juanakatlan',
            'contents_area' => 'ファナカトラン地区',
            'contents_info' => 'バーボン樽16ヶ月熟成',
            'contents_review_flavor' => 'カカオ漂う樽の香り',
            'contents_review_top' => 'ドライでスパイス感の強い口当たり',
            'contents_review_after' => 'ほのかな酸味',
        ],
        // RANCHO LA JOYA
        [
            'title_id' => 'rancholajoya',
            'title_name' => 'RANCHO LA JOYA',
            'alt_name' => 'rancholajoya_blanco',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=7233',
            'image' => 'rancholajoya_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blanco',
            'contents_alc' => '38%/100%AGAVE',
            'contents_dest' => 'ロス・アルトス・ラ・ホヤ蒸留所',
            'contents_nom' => '1555',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'ayotlan',
            'contents_area' => 'アヨトラン地区',
            'contents_info' => '',
            'contents_review_flavor' => '甘く深い香り',
            'contents_review_top' => 'キレのある硬質な舌触り',
            'contents_review_after' => '',
        ],
        // Casco Viejo
        [
            'title_id' => 'cascoviejo',
            'title_name' => 'Casco Viejo',
            'alt_name' => 'cascoviejo_blanco',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=203',
            'image' => 'cascoviejo_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blanco',
            'contents_alc' => '38%/100%AGAVE',
            'contents_dest' => 'カーサ・カマレナ蒸留所',
            'contents_nom' => '1456',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'arandas',
            'contents_area' => 'アランダス地区',
            'contents_info' => '',
            'contents_review_flavor' => '',
            'contents_review_top' => 'キレのある硬質な舌触り',
            'contents_review_after' => '甘く伸びる後味',
        ],
        // EL DESTILADOR
        [
            'title_id' => 'eldestilador',
            'title_name' => 'EL DESTILADOR',
            'alt_name' => 'eldestilador_blanco',
            'url' => 'https://www.tequilamatchmaker.com/tequilas/2428-el-destilador-blanco',
            'image' => 'eldestilador_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blanco',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'ニュートン・エ・イホス蒸留所',
            'contents_nom' => '1173',
            'contents_local_id' => 'centro',
            'contents_local' => 'ソナ・セントロ地方',
            'contents_area_id' => 'zapopan',
            'contents_area' => 'サポパン地区',
            'contents_info' => '',
            'contents_review_flavor' => '爽やかに鼻に抜ける香り',
            'contents_review_top' => '辛い口当たり',
            'contents_review_after' => '',
        ],
        // Tres Alegres Compadres
        [
            'title_id' => 'tresalegrescompadres',
            'title_name' => 'Tres Alegres Compadres',
            'alt_name' => 'tresalegrescompadres_blanco',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=6448',
            'image' => 'tresalegrescompadres_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blanco',
            'contents_alc' => '38%',
            'contents_dest' => 'ラ・コフラディア蒸留所',
            'contents_nom' => '1137',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => '',
            'contents_review_flavor' => '熟成されたような香り',
            'contents_review_top' => '癖の少ない飲みやすさ',
            'contents_review_after' => '',
        ],
        // Hijos de Villa
        [
            'title_id' => 'hijosdevilla',
            'title_name' => 'Hijos de Villa',
            'alt_name' => 'hijosdevilla_blanco',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=7475',
            'image' => 'hijosdevilla_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blanco',
            'contents_alc' => '40%',
            'contents_dest' => 'リコーレス・ヴェラクルス蒸留所',
            'contents_nom' => '1433',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'atotonirco',
            'contents_area' => 'アトトニルコ地区',
            'contents_info' => '',
            'contents_review_flavor' => '強いアガベの草の香り',
            'contents_review_top' => '甘く角のない舌触り',
            'contents_review_after' => '',
        ],
        // GRAN CENTENARIO
        [
            'title_id' => 'grancentenario',
            'title_name' => 'GRAN CENTENARIO',
            'alt_name' => 'grancentenario_anejo',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=3150',
            'image' => 'grancentenario_anejo.jpg',
            'aging_sort' => 'Anejo',
            'aging' => 'Anejo',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'エクセハシエンダ・ロス・カミチネス蒸留所',
            'contents_nom' => '1122',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => 'クエルボ蒸留所の傘下',
            'contents_review_flavor' => '華やかに口の中に広がるバニラの薫香',
            'contents_review_top' => 'まろやかな甘味',
            'contents_review_after' => '',
        ],
        // Chile Cariente
        [
            'title_id' => 'chilecariente',
            'title_name' => 'Chile Cariente',
            'alt_name' => 'chilecariente_blanco',
            'url' => 'http://www.premium-tequila.jp/products/list.php?category_id=232',
            'image' => 'chilecariente_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blanco',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'グルポ・テキレロ・デ・ロスアルトス蒸留所',
            'contents_nom' => '1548',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'arandas',
            'contents_area' => 'アランダス地区',
            'contents_info' => '',
            'contents_review_flavor' => 'アガベ草感残る芳香',
            'contents_review_top' => '甘味の抑えたスパイシーな口当たり',
            'contents_review_after' => 'まろやかな甘味',
        ],
        // Tres Magueyes
        [
            'title_id' => 'tresmagueyes',
            'title_name' => 'Tres Magueyes',
            'alt_name' => 'tresmagueyes_blanco',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=3815',
            'image' => 'tresmagueyes_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blanco',
            'contents_alc' => '38%',
            'contents_dest' => 'ドン・フリオ蒸留所',
            'contents_nom' => '1449',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'atotonirco',
            'contents_area' => 'アトトニルコ地区',
            'contents_info' => '',
            'contents_review_flavor' => 'アガベの爽やかな香り',
            'contents_review_top' => 'スッキリとした苦み',
            'contents_review_after' => '残るアルコール感',
        ],
        // Casino AZUL
        [
            'title_id' => 'casinoazul',
            'title_name' => 'Casino AZUL',
            'alt_name' => 'casinoazul_silver',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=10109',
            'image' => 'casinoazul_silver.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Silver',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'トレス・ムヘレス蒸留所',
            'contents_nom' => '1466',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'amatitan',
            'contents_area' => 'アマティタン地区',
            'contents_info' => '',
            'contents_review_flavor' => '芳醇なアガベの香り',
            'contents_review_top' => 'ほのかなスパイスと甘み',
            'contents_review_after' => '',
        ],
        // EL PADRINO
        [
            'title_id' => 'elpadrino',
            'title_name' => 'EL PADRINO',
            'alt_name' => 'elpadrino_blanco',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=7565',
            'image' => 'elpadrino_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blanco',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'デル・バジェ・デ・テキーラ蒸留所',
            'contents_nom' => '1438',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'amatitan',
            'contents_area' => 'アマティタン地区',
            'contents_info' => '',
            'contents_review_flavor' => '柔らかにアガベが薫る',
            'contents_review_top' => 'さらりとした口当たりで飲みやすい',
            'contents_review_after' => '',
        ],
        // LA COFRADIA
        [
            'title_id' => 'lacofradia',
            'title_name' => 'LA COFRADIA',
            'alt_name' => 'lacofradia_anejo',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=943',
            'image' => 'lacofradia_anejo.jpg',
            'aging_sort' => 'Anejo',
            'aging' => 'Anejo',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'ラ・コフラディア蒸留所',
            'contents_nom' => '1137',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => '12ヶ月樽熟成',
            'contents_review_flavor' => '樽の発酵感を感じる柔らかな香り',
            'contents_review_top' => 'カラメルのような甘み',
            'contents_review_after' => 'キレのある酸味 ',
        ],
        // DONA CELIA
        [
            'title_id' => 'donacelia',
            'title_name' => 'DONA CELIA',
            'alt_name' => 'donacelia_reposado',
            'url' => 'https://www.premium-tequila.jp/products/detail.php?product_id=261',
            'image' => 'donacelia_reposado.jpg',
            'aging_sort' => 'Reposado',
            'aging' => 'Reposado',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'デル・バジェ・デ・テキーラ蒸留所',
            'contents_nom' => '1438',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => '',
            'contents_review_flavor' => '鼻に広がる芯のあるカカオの香り',
            'contents_review_top' => '甘みと微かな酸味のキレの共存',
            'contents_review_after' => '締まりのあるアルコール感',
        ],
        [
            'title_id' => 'donacelia',
            'title_name' => 'DONA CELIA',
            'alt_name' => 'donacelia_anejo',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=262',
            'image' => 'donacelia_anejo.jpg',
            'aging_sort' => 'Anejo',
            'aging' => 'Anejo',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'デル・バジェ・デ・テキーラ蒸留所',
            'contents_nom' => '1438',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => '1～3年アメリカンオーク樽熟成',
            'contents_review_flavor' => 'ビターカカオのような強い香り',
            'contents_review_top' => 'すっきりとした酸味の口当たり',
            'contents_review_after' => 'はっきりとした甘みの後味',
        ],
        // Don Fernando
        [
            'title_id' => 'donfernando',
            'title_name' => 'Don Fernando',
            'alt_name' => 'donfernando_anejo',
            'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=176',
            'image' => 'donfernando_anejo.jpg',
            'aging_sort' => 'Anejo',
            'aging' => 'Anejo',
            'contents_alc' => '38%/100%AGAVE',
            'contents_dest' => 'バランカ・デ・アマティタン蒸留所',
            'contents_nom' => '1473',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'amatitan',
            'contents_area' => 'アマティタン地区',
            'contents_info' => '24ヶ月フレンチオーク樽熟成',
            'contents_review_flavor' => '樽の発酵香とほんのり甘い香り',
            'contents_review_top' => 'カカオのような甘い口当たり',
            'contents_review_after' => '酸味がするっと飲みやすい',
        ],
        // Rehilete PAPALOTE
        [
            'title_id' => 'rehiletepapalote',
            'title_name' => 'Rehilete PAPALOTE',
            'alt_name' => 'rehilete_papalote_blanco',
            'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=10162',
            'image' => 'rehilete_papalote_blanco.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Blanco',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'グルポ・テキレロ・デ・ロスアルトス蒸留所',
            'contents_nom' => '1548',
            'contents_local_id' => 'altos',
            'contents_local' => 'ロスアルトス地方',
            'contents_area_id' => 'arandas',
            'contents_area' => 'アランダス地区',
            'contents_info' => '',
            'contents_review_flavor' => '爽やかながら発酵感のあるアガベの香り',
            'contents_review_top' => 'するりと澄み渡る滑らかな舌触り',
            'contents_review_after' => '軽い甘みと微かな酸味の後味',
        ],
        // Hussong's
        [
            'title_id' => 'hussongs',
            'title_name' => 'Hussong\'s',
            'alt_name' => 'hussans_reposado',
            'url' => 'https://www.premium-tequila.jp/products/detail.php?product_id=237',
            'image' => 'hussans_reposado.jpg',
            'aging_sort' => 'Reposado',
            'aging' => 'Reposado',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'レイロス蒸留所',
            'contents_nom' => '1489',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => '',
            'contents_review_flavor' => 'ほんのり爽快な発酵感があり、繊細で滑らかな香り',
            'contents_review_top' => '甘みがありながらも、スムースな飲み口',
            'contents_review_after' => 'すーっと優しいクセのなさ',
        ],
        // TESORO AZUL
        [
            'title_id' => 'tesoroazul',
            'title_name' => 'TESORO AZUL',
            'alt_name' => 'tesoro_azul_silver',
            'url' => 'https://buyee.jp/item/yahoo/shopping/chagatapark_3248-645503?lang=ja',
            'image' => 'tesoro_azul_silver.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Silver',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => 'フィノス・デ・アガベ蒸留所',
            'contents_nom' => '1416',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => '',
            'contents_review_flavor' => '発酵感が心地よくアガベが薫る',
            'contents_review_top' => 'さらりとした飲み口',
            'contents_review_after' => '多少アルコール感の残る後味',
        ],
        // Santo
        [
            'title_id' => 'santo',
            'title_name' => 'Santo',
            'alt_name' => 'santo_mezquila_blanaco',
            'url' => 'https://wazawaza.jp/products/detail.php?product_id=725',
            'image' => 'santo_mezquila_blanaco.jpg',
            'aging_sort' => 'Others',
            'aging' => 'Mezquila Blanco',
            'contents_alc' => '40%/100%AGAVE',
            'contents_dest' => '-',
            'contents_nom' => '-',
            'contents_local_id' => 'centro',
            'contents_local' => 'ソナ・セントロ地方',
            'contents_area_id' => '-',
            'contents_area' => '-',
            'contents_info' => 'テキーラとメスカルを5:5で作成したメスキーラ',
            'contents_review_flavor' => '二種のアガベを使った、強くもまろやかな草の爽香',
            'contents_review_top' => '甘味&硬めの舌触り',
            'contents_review_after' => 'テキーラの発酵とメスカルの爽快さの融合したまろやかさ',
        ],
        // Los Corrales
        [
            'title_id' => 'loscorrales',
            'title_name' => 'Los Corrales',
            'alt_name' => 'loscorrales_gold',
            'url' => 'https://www.tequilamatchmaker.com/tequilas/3733-los-corrales-reposado',
            'image' => 'loscorrales_gold.jpg',
            'aging_sort' => 'Gold',
            'aging' => 'Gold',
            'contents_alc' => '38%',
            'contents_dest' => 'ニュートン・エ・イホス蒸留所',
            'contents_nom' => '1173',
            'contents_local_id' => 'centro',
            'contents_local' => 'ソナ・セントロ地方',
            'contents_area_id' => 'zapopan',
            'contents_area' => 'サポパン地区',
            'contents_info' => '',
            'contents_review_flavor' => 'するりと柔らかなマイルドな香り',
            'contents_review_top' => '少しとろみのある甘い舌触り',
            'contents_review_after' => 'アルコール感ありながらも滑らか',
        ],
        // Tres Sombreros
        [
            'title_id' => 'tressombreros',
            'title_name' => 'Tres Sombreros',
            'alt_name' => 'tressombreros_silver',
            'url' => 'https://www.amazon.co.jp/%E3%83%88%E3%83%AC%E3%82%B9%E3%83%BB%E3%82%BD%E3%83%B3%E3%83%96%E3%83%AC%E3%83%AD%E3%82%B9-12878-%E3%82%B7%E3%83%AB%E3%83%90%E3%83%BC-%E3%83%86%E3%82%AD%E3%83%BC%E3%83%A9-700ml/dp/B00AFBJE24',
            'image' => 'tressombreros_silver.jpg',
            'aging_sort' => 'Blanco',
            'aging' => 'Silver',
            'contents_alc' => '38%',
            'contents_dest' => 'テキレラ・ラ・マグダレナ蒸留所',
            'contents_nom' => '1463',
            'contents_local_id' => 'centro',
            'contents_local' => 'ソナ・セントロ地方',
            'contents_area_id' => 'zapopan',
            'contents_area' => 'サポパン地区',
            'contents_info' => '81%アガベのミクスト',
            'contents_review_flavor' => '柔らかな甘みの鼻通り',
            'contents_review_top' => '舌に転がる滑らかな甘み',
            'contents_review_after' => 'さっぱりと微アガベのアルコール感',
        ],
        // Lokita
        [
            'title_id' => 'lokita',
            'title_name' => 'Lokita',
            'alt_name' => 'lokita_gold',
            'url' => 'https://www.amazon.co.jp/%E3%83%AD%E3%82%AD%E3%83%BC%E3%82%BF-%E3%82%B4%E3%83%BC%E3%83%AB%E3%83%89-700ml-%E3%83%96%E3%83%AB%E3%83%BC%E3%82%A2%E3%82%AC%E3%83%99100%EF%BC%85-%E3%82%B9%E3%83%94%E3%83%AA%E3%83%83%E3%83%84/dp/B07XCHVBVD',
            'image' => 'lokita_gold.jpg',
            'aging_sort' => 'Gold',
            'aging' => 'Gold',
            'contents_alc' => '35%/100%AGAVE',
            'contents_dest' => 'フィノス・デ・アガベ蒸留所',
            'contents_nom' => '1416',
            'contents_local_id' => 'valles',
            'contents_local' => 'バジェス地方',
            'contents_area_id' => 'tequila',
            'contents_area' => 'テキーラ地区',
            'contents_info' => '',
            'contents_review_flavor' => '樽熟成とアガベの甘い香り',
            'contents_review_top' => 'アガベの甘さが際立つ旨み',
            'contents_review_after' => '微かなアルコール感と苦味',
        ],
    ];
}
