<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class CreateSyouhinTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        // カラム作成
        Schema::create('syouhin', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('class_name')->comment('ブランド名');
            $table->string('alt_name')->comment('種類');
            $table->string('url')->comment('商品の外部URL');
            $table->string('image')->comment('イメージ画像');
            $table->string('aging')->comment('熟成名称');
            $table->string('contents_alc')->comment('度数');
            $table->string('contents_dest')->comment('蒸留所');
            $table->string('contents_nom')->comment('蒸留所番号');
            $table->string('contents_area')->comment('蒸留エリア');
            $table->string('contents_info')->comment('情報');
            $table->string('contents_review_flavor')->comment('レビュー：香り');
            $table->string('contents_review_top')->comment('レビュー：トップノート');
            $table->string('contents_review_after')->comment('レビュー：後味');
            $table->timestamps();
        });

        // データに挿入する値の定義
        $syouhin = [
            // Sauza
            [
                'class_name' => 'sauza',
                'alt_name' => 'sauza_silver',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=753',
                'image' => 'sauza_silver.jpg',
                'aging' => 'Silver',
                'contents_alc' => '40%',
                'contents_dest' => 'サウザ蒸留所',
                'contents_nom' => '1102',
                'contents_area' => 'バジェス地方/テキーラ地区',
                'contents_info' => '',
                'contents_review_flavor' => '',
                'contents_review_top' => '',
                'contents_review_after' => '爽やかな香りとキレのある王道テイスト',
            ],
            [
                'class_name' => 'sauza',
                'alt_name' => 'sauza_gold',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=754',
                'image' => 'sauza_gold.jpg',
                'aging' => 'Gold',
                'contents_alc' => '40%',
                'contents_dest' => 'サウザ蒸留所',
                'contents_nom' => '1102',
                'contents_area' => 'バジェス地方/テキーラ地区',
                'contents_info' => '',
                'contents_review_flavor' => '',
                'contents_review_top' => '',
                'contents_review_after' => '爽快なキレの良さを残しつつ滑らかな風味',
            ],
            [
                'class_name' => 'sauza',
                'alt_name' => 'sauza_blue_silver',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=9796',
                'image' => 'sauza_blue_silver.jpg',
                'aging' => 'Blue Silver',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'サウザ蒸留所',
                'contents_nom' => '1102',
                'contents_area' => 'バジェス地方/テキーラ地区',
                'contents_info' => '',
                'contents_review_flavor' => '',
                'contents_review_top' => '',
                'contents_review_after' => '雑味が少ない爽快な香りが広がる',
            ],
            [
                'class_name' => 'sauza',
                'alt_name' => 'sauza_three_generations',
                'url' => 'https://sake.biccamera.com/bs/item/3285766/',
                'image' => 'sauza_three_generations.jpg',
                'aging' => 'Tres Generaciones Plata',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'サウザ蒸留所',
                'contents_nom' => '1102',
                'contents_area' => 'バジェス地方/テキーラ地区',
                'contents_info' => '',
                'contents_review_flavor' => '',
                'contents_review_top' => '',
                'contents_review_after' => '爽やかながら芯のあるアガベ感',
            ],
                // Jose Cuervo
            [
                'class_name' => 'josecuervo',
                'alt_name' => 'cuervo_silver',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=3084',
                'image' => 'cuervo_silver.jpg',
                'aging' => 'Especial Silver',
                'contents_alc' => '40%',
                'contents_dest' => 'クエルボ蒸留所',
                'contents_nom' => '1122',
                'contents_area' => 'バジェス地方/テキーラ地区',
                'contents_info' => '',
                'contents_review_flavor' => '甘さ引き立つ上品漂う香り',
                'contents_review_top' => '',
                'contents_review_after' => '',
            ],
            [
                'class_name' => 'josecuervo',
                'alt_name' => 'cuervo_reposado',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=738',
                'image' => 'cuervo_reposado.jpg',
                'aging' => 'Especial Reposado',
                'contents_alc' => '40%',
                'contents_dest' => 'クエルボ蒸留所',
                'contents_nom' => '1122',
                'contents_area' => 'バジェス地方/テキーラ地区',
                'contents_info' => '',
                'contents_review_flavor' => '',
                'contents_review_top' => '樽熟成による芯のある深みと滑らかさ',
                'contents_review_after' => '',
            ],
            [
                'class_name' => 'josecuervo',
                'alt_name' => 'cuervo_traditional_silver',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=10315',
                'image' => 'cuervo_traditional_silver.jpg',
                'aging' => 'Traditional Silver',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'クエルボ蒸留所',
                'contents_nom' => '1122',
                'contents_area' => 'バジェス地方/テキーラ地区',
                'contents_info' => '',
                'contents_review_flavor' => 'アガベの雑味が少ない甘味と上品な芳香',
                'contents_review_top' => '',
                'contents_review_after' => '',
            ],
            [
                'class_name' => 'josecuervo',
                'alt_name' => '1800_silver',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=739',
                'image' => '1800_silver.jpg',
                'aging' => '1800 Silver',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'クエルボ蒸留所',
                'contents_nom' => '1122',
                'contents_area' => 'バジェス地方/テキーラ地区',
                'contents_info' => '',
                'contents_review_flavor' => '',
                'contents_review_top' => '',
                'contents_review_after' => '柔和で甘い爽快感とスパイシーなキレの融合',
            ],
            [
                'class_name' => 'josecuervo',
                'alt_name' => '1800_reposado',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=64',
                'image' => '1800_reposado.jpg',
                'aging' => '1800 Reposado',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'クエルボ蒸留所',
                'contents_nom' => '1122',
                'contents_area' => 'バジェス地方/テキーラ地区',
                'contents_info' => '',
                'contents_review_flavor' => '甘いすっきりとした香り',
                'contents_review_top' => '透き通った爽やかな甘味',
                'contents_review_after' => '滑らかな飲み心地',
            ],
            // Olmeca
            [
                'class_name' => 'olmeca',
                'alt_name' => 'olmeca_blanco',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=747',
                'image' => 'olmeca_blanco.jpg',
                'aging' => 'Blanco',
                'contents_alc' => '40%',
                'contents_dest' => 'ペルノ・リカール蒸留所',
                'contents_nom' => '1111',
                'contents_area' => 'ロスアルトス地方/アランダス地区',
                'contents_info' => '',
                'contents_review_flavor' => '',
                'contents_review_top' => '上品で甘さ控えめでドライなテイスト',
                'contents_review_after' => '',
            ],
            [
                'class_name' => 'olmeca',
                'alt_name' => 'olmeca_reposado',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=748',
                'image' => 'olmeca_reposado.jpg',
                'aging' => 'Reposado',
                'contents_alc' => '40%',
                'contents_dest' => 'ペルノ・リカール蒸留所',
                'contents_nom' => '1111',
                'contents_area' => 'ロスアルトス地方/アランダス地区',
                'contents_info' => '',
                'contents_review_flavor' => '',
                'contents_review_top' => 'スパイス香るショット向きな大人テイスト',
                'contents_review_after' => '',
            ],
            // mariachi
            [
                'class_name' => 'mariachi',
                'alt_name' => 'mariachi_silver',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=745',
                'image' => 'mariachi_silver.jpg',
                'aging' => 'Silver',
                'contents_alc' => '40%',
                'contents_dest' => 'ペルノ・リカール蒸留所',
                'contents_nom' => '1111',
                'contents_area' => 'ロスアルトス地方/アランダス地区',
                'contents_info' => '',
                'contents_review_flavor' => '',
                'contents_review_top' => '上品でまろやかな口当たり',
                'contents_review_after' => '',
            ],
            [
                'class_name' => 'mariachi',
                'alt_name' => 'mariachi_gold',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=746',
                'image' => 'mariachi_gold.jpg',
                'aging' => 'Gold',
                'contents_alc' => '40%',
                'contents_dest' => 'ペルノ・リカール蒸留所',
                'contents_nom' => '1111',
                'contents_area' => 'ロスアルトス地方/アランダス地区',
                'contents_info' => '',
                'contents_review_flavor' => '',
                'contents_review_top' => 'スパイシーな香りとまろやかな甘さ',
                'contents_review_after' => '',
            ],
            // Alacran
            [
                'class_name' => 'alacran',
                'alt_name' => 'alacran_blanco',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=14',
                'image' => 'alacran_blanco.jpg',
                'aging' => 'Blanco',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'フィノス・デ・アガベ蒸留所',
                'contents_nom' => '1416',
                'contents_area' => 'バジェス地方/テキーラ地区',
                'contents_info' => '',
                'contents_review_flavor' => 'サイダーのような爽やかな香り',
                'contents_review_top' => '甘い口当たり',
                'contents_review_after' => '',
            ],
            [
                'class_name' => 'alacran',
                'alt_name' => 'alacran_crystal_anejo',
                'url' => 'https://wazawaza.jp/products/detail.php?product_id=601',
                'image' => 'alacran_crystal_anejo.jpg',
                'aging' => 'Crystal Anejo',
                'contents_alc' => '35%/100%AGAVE',
                'contents_dest' => 'フィノス・デ・アガベ蒸留所',
                'contents_nom' => '1416',
                'contents_area' => 'バジェス地方/テキーラ地区',
                'contents_info' => '',
                'contents_review_flavor' => 'クリームソーダ風の爽やかな香り',
                'contents_review_top' => 'バニラと蜂蜜を思わすまろやかさ',
                'contents_review_after' => '滑らかな舌触りと酸味のある後味',
            ],
            // AHA TORO
            [
                'class_name' => 'ahatoro',
                'alt_name' => 'ahatoro_blanco',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=15',
                'image' => 'ahatoro_blanco.jpg',
                'aging' => 'Blanco',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'グルポ・テキレロ・デ・ロスアルトス蒸留所',
                'contents_nom' => '1548',
                'contents_area' => 'ロスアルトス地方/アランダス地区',
                'contents_info' => '',
                'contents_review_flavor' => '甘く優しい香り',
                'contents_review_top' => '',
                'contents_review_after' => 'キレのある苦み',
            ],
            [
                'class_name' => 'ahatoro',
                'alt_name' => 'ahatoro_anejo',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=17',
                'image' => 'ahatoro_anejo.jpg',
                'aging' => 'Anejo',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'グルポ・テキレロ・デ・ロスアルトス蒸留所',
                'contents_nom' => '1548',
                'contents_area' => 'ロスアルトス地方/アランダス地区',
                'contents_info' => '',
                'contents_review_flavor' => '',
                'contents_review_top' => '熟成しつつもあっさりとした飲み口',
                'contents_review_after' => '',
            ],
            // El Tesoro
            [
                'class_name' => 'eltesoro',
                'alt_name' => 'eltesoro_anejo',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=173',
                'image' => 'eltesoro_anejo.jpg',
                'aging' => 'Paradiso Anejo',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'ラ・アルテ－ニャ蒸留所',
                'contents_nom' => '1139',
                'contents_area' => 'ロスアルトス地方/アランダス地区',
                'contents_info' => 'コニャック樽で60ヶ月熟成',
                'contents_review_flavor' => '5年熟成の少し酸味ある香り',
                'contents_review_top' => '控えめな甘さ',
                'contents_review_after' => '',
            ],
            //Agavale
            [
                'class_name' => 'agavales',
                'alt_name' => 'agavales_blanco',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=76',
                'image' => 'agavales_blanco.jpg',
                'aging' => 'Blanco',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'デル・バジェ・デ・テキーラ蒸留所',
                'contents_nom' => '1438',
                'contents_area' => 'バジェス地方/テキーラ地区',
                'contents_info' => '',
                'contents_review_flavor' => '',
                'contents_review_top' => '甘味が少なく辛みの感じるキレ',
                'contents_review_after' => '',
            ],
            // Ole
            [
                'class_name' => 'ole',
                'alt_name' => 'ole_silver',
                'url' => 'https://www.miraido-onlineshop.com/item/7-ole-tequila-40/',
                'image' => 'ole_silver.jpg',
                'aging' => 'Silver',
                'contents_alc' => '40%',
                'contents_dest' => 'ゴンザレス・ゴンザレス蒸留所',
                'contents_nom' => '1143',
                'contents_area' => 'ソナ・セントロ地方/サポパン地区',
                'contents_info' => '',
                'contents_review_flavor' => '漂うスパイシーな香り',
                'contents_review_top' => 'キレもある飲みやすさ',
                'contents_review_after' => '',
            ],
            // Orendain
            [
                'class_name' => 'orendain',
                'alt_name' => 'orendain_blanco',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=750',
                'image' => 'orendain_blanco.jpg',
                'aging' => 'Blanco',
                'contents_alc' => '40%',
                'contents_dest' => 'オレンダイン蒸留所',
                'contents_nom' => '1110',
                'contents_area' => 'バジェス地方/テキーラ地区',
                'contents_info' => '',
                'contents_review_flavor' => '深みのある爽やかな芳香',
                'contents_review_top' => '甘くなめらか',
                'contents_review_after' => '',
            ],
            // Camino
            [
                'class_name' => 'camino',
                'alt_name' => 'camino_blanco',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=743',
                'image' => 'camino_blanco.jpg',
                'aging' => 'Blanco',
                'contents_alc' => '35%',
                'contents_dest' => 'カミノ・レアル蒸留所',
                'contents_nom' => '1487',
                'contents_area' => 'ロスアルトス地方/アランダス地区',
                'contents_info' => '',
                'contents_review_flavor' => 'フレッシュなアガベの優しい香り',
                'contents_review_top' => '滑らかな口当たりの飲みやすさ',
                'contents_review_after' => '',
            ],
            [
                'class_name' => 'camino',
                'alt_name' => '',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=744',
                'image' => 'camino_gold.jpg',
                'aging' => 'Gold',
                'contents_alc' => '40%',
                'contents_dest' => 'カミノ・レアル蒸留所',
                'contents_nom' => '1487',
                'contents_area' => 'ロスアルトス地方/アランダス地区',
                'contents_info' => '',
                'contents_review_flavor' => '滑らかな発酵の香り',
                'contents_review_top' => '豊かな甘さ',
                'contents_review_after' => '',
            ],
            // El Charro
            [
                'class_name' => 'elcharro',
                'alt_name' => 'elcharro_silver',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=234',
                'image' => 'elcharro_silver.jpg',
                'aging' => 'Silver',
                'contents_alc' => '38%',
                'contents_dest' => 'カンパニャ・テキレラ・デ・アランダス蒸留所',
                'contents_nom' => '1460',
                'contents_area' => 'ロスアルトス地方/アランダス地区',
                'contents_info' => '',
                'contents_review_flavor' => 'スッキリと鼻に抜ける香り',
                'contents_review_top' => '滑らかな口当たり',
                'contents_review_after' => '',
            ],
            //  Herradura
            [
                'class_name' => 'herradura',
                'alt_name' => 'herradura_plata',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=89',
                'image' => 'herradura_plata.jpg',
                'aging' => 'Plata',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'カーサ・エラドゥーラ蒸留所',
                'contents_nom' => '1119',
                'contents_area' => 'バジェス地方/アマティタン地区',
                'contents_info' => '',
                'contents_review_flavor' => '樽の発酵香とほのかなスパイシーさ',
                'contents_review_top' => '程よい甘さ',
                'contents_review_after' => '',
            ],
            // Corralejo
            [
                'class_name' => 'corralejo',
                'alt_name' => 'corralejo_anejo',
                'url' => 'https://www.premium-tequila.jp/products/detail.php?product_id=116',
                'image' => 'corralejo_anejo.jpg',
                'aging' => 'Anejo',
                'contents_alc' => '38%/100%AGAVE',
                'contents_dest' => 'コラレホ蒸留所',
                'contents_nom' => '1368',
                'contents_area' => 'グアナファト州 ペンハモ地区',
                'contents_info' => 'テネシーウィスキー樽で1年熟成',
                'contents_review_flavor' => '熟成したシナモンのような深い香り',
                'contents_review_top' => 'バニラ引き立つ甘み',
                'contents_review_after' => '',
            ],
            // Cazadores
            [
                'class_name' => 'cazadores',
                'alt_name' => 'cazadores_blanco',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=61',
                'image' => 'cazadores_blanco.jpg',
                'aging' => 'Blanco',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'カサドレス蒸留所',
                'contents_nom' => '1487',
                'contents_area' => 'ロスアルトス地方/アランダス地区',
                'contents_info' => '',
                'contents_review_flavor' => '上品でややスパイシーなハーブ香',
                'contents_review_top' => '滑らかな舌触り',
                'contents_review_after' => '',
            ],
            [
                'class_name' => 'cazadores',
                'alt_name' => 'cazadores_anejo',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=63',
                'image' => 'cazadores_anejo.jpg',
                'aging' => 'Anejo',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'カサドレス蒸留所',
                'contents_nom' => '1487',
                'contents_area' => 'ロスアルトス地方/アランダス地区',
                'contents_info' => 'アメリカンオークの新樽で18ヶ月熟成',
                'contents_review_flavor' => '薫るアガベの爽やかさ',
                'contents_review_top' => 'バニラのような熟成したコク',
                'contents_review_after' => '',
            ],
            // Porfidio
            [
                'class_name' => 'porfidio',
                'alt_name' => 'porfidio_silver',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=96',
                'image' => 'porfidio_silver.jpg',
                'aging' => 'Silver',
                'contents_alc' => '39.5%/100%AGAVE',
                'contents_dest' => 'インモビリアリア・マスト蒸留所',
                'contents_nom' => '1462',
                'contents_area' => 'バジェス地方/ラス・フンタス地区',
                'contents_info' => '厳密にはテキーラではない',
                'contents_review_flavor' => '複雑ながらすっきりとした芳醇な香り',
                'contents_review_top' => '丸みのある爽やかな飲み口',
                'contents_review_after' => '',
            ],
            // Casa de luna
            [
                'class_name' => 'casadeluna',
                'alt_name' => 'casadeluna_blanco',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=4',
                'image' => 'casadeluna_blanco.jpg',
                'aging' => 'Blanco',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'ファナカトラン蒸留所',
                'contents_nom' => '1551',
                'contents_area' => 'ソナ・セントロ地方/ファナカトラン地区',
                'contents_info' => '',
                'contents_review_flavor' => '優しく鼻通る香り',
                'contents_review_top' => '滑らかな舌触り',
                'contents_review_after' => '少しのアルコール感',
            ],
            // Tresreyes
            [
                'class_name' => 'tresreyes',
                'alt_name' => 'tresreyes_silver',
                'url' => 'https://www.miraido-onlineshop.com/item/7-tres-reyes-s/',
                'image' => 'tresreyes_silver.jpg',
                'aging' => 'Silver',
                'contents_alc' => '38%',
                'contents_dest' => 'カンパニャ・テキレラ・デ・アランダス蒸留所',
                'contents_nom' => '1460',
                'contents_area' => 'ロスアルトス地方/アランダス地区',
                'contents_info' => '',
                'contents_review_flavor' => '',
                'contents_review_top' => 'ビターな口当たり',
                'contents_review_after' => '甘みのある後味',
            ],
            // El jimador
            [
                'class_name' => 'eljimador',
                'alt_name' => 'eljimador_blanco',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=101',
                'image' => 'eljimador_blanco.jpg',
                'aging' => 'Blanco',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'カーサ・エラドゥーラ蒸留所',
                'contents_nom' => '1119',
                'contents_area' => 'バジェス地方/アマティタン地区',
                'contents_info' => '',
                'contents_review_flavor' => 'サイダーのような爽やかな香り',
                'contents_review_top' => 'ほんのりスパイシー',
                'contents_review_after' => '',
            ],
            // Don jurio
            [
                'class_name' => 'donjurio',
                'alt_name' => 'donjurio_blanco',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=14797',
                'image' => 'donjurio_blanco.jpg',
                'aging' => 'Blanco',
                'contents_alc' => '38%/100%AGAVE',
                'contents_dest' => 'ドン・フリオ蒸留所',
                'contents_nom' => '1449',
                'contents_area' => 'ロスアルトス地方/アトトニルコ地区',
                'contents_info' => '',
                'contents_review_flavor' => '澄み渡ったまろやかな香り',
                'contents_review_top' => '適度な甘味',
                'contents_review_after' => '',
            ],
            [
                'class_name' => 'donjurio',
                'alt_name' => 'donjurio_anejo',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=68',
                'image' => 'donjurio_anejo.jpg',
                'aging' => 'Anejo',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'ドン・フリオ蒸留所',
                'contents_nom' => '1449',
                'contents_area' => 'ロスアルトス地方/アトトニルコ地区',
                'contents_info' => 'アメリカンオーク樽で18ヶ月熟成',
                'contents_review_flavor' => 'コーヒー、バニラのようなまろやかなコクの熟成',
                'contents_review_top' => '蜂蜜に適度な酸味を感じる甘み',
                'contents_review_after' => '',
            ],
            // Casa noble
            [
                'class_name' => 'casanoble',
                'alt_name' => 'casanoble_blanco',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=72',
                'image' => 'casanoble_blanco.jpg',
                'aging' => 'Crystal Blanco',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'ラ・コフラディア蒸留所',
                'contents_nom' => '1137',
                'contents_area' => 'バジェス地方/テキーラ地区',
                'contents_info' => '',
                'contents_review_flavor' => '爽やかなアガベの甘味香',
                'contents_review_top' => '滑らかな口当たり',
                'contents_review_after' => 'ほんのりシトラスの発光感',
            ],
            [
                'class_name' => 'casanoble',
                'alt_name' => 'casanoble_reposado',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=73',
                'image' => 'casanoble_reposado.jpg',
                'aging' => 'Reposado',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'ラ・コフラディア蒸留所',
                'contents_nom' => '1137',
                'contents_area' => 'バジェス地方/テキーラ地区',
                'contents_info' => 'フレンチオーク樽364日熟成',
                'contents_review_flavor' => '後から香るアガベ感',
                'contents_review_top' => 'カカオ香る甘み',
                'contents_review_after' => 'シトラスな後味',
            ],
            [
                'class_name' => 'casanoble',
                'alt_name' => 'casanoble_anejo',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=74',
                'image' => 'casanoble_anejo.jpg',
                'aging' => 'Anejo',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'ラ・コフラディア蒸留所',
                'contents_nom' => '1137',
                'contents_area' => 'バジェス地方/テキーラ地区',
                'contents_info' => 'フレンチオークの新樽で24ヶ月熟成',
                'contents_review_flavor' => '芳醇で濃厚なカカオ香',
                'contents_review_top' => 'チョコのような甘味',
                'contents_review_after' => '',
            ],
            // Kah
            [
                'class_name' => 'kah',
                'alt_name' => 'kah_anejo',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=171',
                'image' => 'kah_anejo.jpg',
                'aging' => 'Anejo',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'テキーラス・フィノス蒸留所',
                'contents_nom' => '1472',
                'contents_area' => 'バジェス地方/テキーラ地区',
                'contents_info' => 'アメリカンオーク樽で2年の熟成',
                'contents_review_flavor' => '繊細でやさしい香り',
                'contents_review_top' => 'シトラスでほのかな甘み',
                'contents_review_after' => '',
            ],
            // Patron
            [
                'class_name' => 'patron',
                'alt_name' => 'patron_silver',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=58',
                'image' => 'patron_silver.jpg',
                'aging' => 'Silver',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'パトロン蒸留所',
                'contents_nom' => '1492',
                'contents_area' => 'ロスアルトス地方/アトトニルコ地区',
                'contents_info' => '',
                'contents_review_flavor' => '果実の複雑なシトラスとアガベ感じる香り',
                'contents_review_top' => 'ほのかなスパイス感とスムースな口当たり',
                'contents_review_after' => '蜂蜜のような甘み後味',
            ],
            [
                'class_name' => 'patron',
                'alt_name' => 'patron_reposado',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=59',
                'image' => 'patron_reposado.jpg',
                'aging' => 'Reposado',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'パトロン蒸留所',
                'contents_nom' => '1492',
                'contents_area' => 'ロスアルトス地方/アトトニルコ地区',
                'contents_info' => 'アメリカンオーク樽で6ヶ月熟成ブレンド',
                'contents_review_flavor' => 'シトラスで爽やかな香',
                'contents_review_top' => 'スパイス混ざる複雑なキレのある味',
                'contents_review_after' => '蜂蜜のような甘い樽の残り香',
            ],
            [
                'class_name' => 'patron',
                'alt_name' => 'patron_anejo',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=60',
                'image' => 'patron_anejo.jpg',
                'aging' => 'Anejo',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'パトロン蒸留所',
                'contents_nom' => '1492',
                'contents_area' => 'ロスアルトス地方/アトトニルコ地区',
                'contents_info' => 'アメリカン/フレンチオーク樽で12ヶ月熟成ブレンド',
                'contents_review_flavor' => 'シトラスでまろやかな香',
                'contents_review_top' => '複雑なスパイスと丸みを帯びた味',
                'contents_review_after' => 'バニラのような深みのある甘みと樽香',
            ],
            // Latilica
            [
                'class_name' => 'latilica',
                'alt_name' => 'latilica_blanco',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=9500',
                'image' => 'latilica_blanco.jpg',
                'aging' => 'Blanco',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'ファナカトラン蒸留所',
                'contents_nom' => '1551',
                'contents_area' => 'ソナ・セントロ地方ファナカトラン地区',
                'contents_info' => '',
                'contents_review_flavor' => '',
                'contents_review_top' => '芯のあるコクと苦みと硬質な舌触り',
                'contents_review_after' => '',
            ],
            // Muchaliga
            [
                'class_name' => 'muchaliga',
                'alt_name' => '',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=200',
                'image' => 'muchaliga_blanco.jpg',
                'aging' => 'Blanco(ブラーヴォ)',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'ファナカトラン蒸留所',
                'contents_nom' => '1551',
                'contents_area' => 'ソナ・セントロ地方/ファナカトラン地区',
                'contents_info' => '',
                'contents_review_flavor' => 'しっかりとしたアガベの香り',
                'contents_review_top' => 'マイルドでスムースな口当たり',
                'contents_review_after' => 'シンプルにほのかな甘み',
            ],
            [
                'class_name' => 'muchaliga',
                'alt_name' => 'muchaliga_reposado',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=201',
                'image' => 'muchaliga_reposado.jpg',
                'aging' => 'Reposado(カニバル)',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'ファナカトラン蒸留所',
                'contents_nom' => '1551',
                'contents_area' => 'ソナ・セントロ地方/ファナカトラン地区',
                'contents_info' => 'バーボン樽で3ヶ月熟成',
                'contents_review_flavor' => '甘いカカオ樽香',
                'contents_review_top' => 'すっきりな酸味',
                'contents_review_after' => 'ほのかにスパイシーな後味',
            ],
            [
                'class_name' => 'muchaliga',
                'alt_name' => 'muchaliga_anejo',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=202',
                'image' => 'muchaliga_anejo.jpg',
                'aging' => 'Anejo(インヴィクト)',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'ファナカトラン蒸留所',
                'contents_nom' => '1551',
                'contents_area' => 'ソナ・セントロ地方/ファナカトラン地区',
                'contents_info' => 'バーボン樽16ヶ月熟成',
                'contents_review_flavor' => 'カカオ漂う樽の香り',
                'contents_review_top' => 'ドライでスパイス感の強い口当たり',
                'contents_review_after' => 'ほのかな酸味',
            ],
            // Rancholajoya
            [
                'class_name' => 'rancholajoya',
                'alt_name' => 'rancholajoya_blanco',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=7233',
                'image' => 'rancholajoya_blanco.jpg',
                'aging' => 'Blanco',
                'contents_alc' => '38%/100%AGAVE',
                'contents_dest' => 'ロス・アルトス・ラ・ホヤ蒸留所',
                'contents_nom' => '1555',
                'contents_area' => 'ロスアルトス地方/アヨトラン地区',
                'contents_info' => '',
                'contents_review_flavor' => '甘く深い香り',
                'contents_review_top' => 'キレのある硬質な舌触り',
                'contents_review_after' => '',
            ],
            // Cascoviejo
            [
                'class_name' => 'cascoviejo',
                'alt_name' => 'cascoviejo_blanco',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=203',
                'image' => 'cascoviejo_blanco.jpg',
                'aging' => 'Blanco',
                'contents_alc' => '38%/100%AGAVE',
                'contents_dest' => 'カーサ・カマレナ蒸留所',
                'contents_nom' => '1456',
                'contents_area' => 'ロスアルトス地方/アランダス地区',
                'contents_info' => '',
                'contents_review_flavor' => '',
                'contents_review_top' => 'キレのある硬質な舌触り',
                'contents_review_after' => '甘く伸びる後味',
            ],
            // El destilador
            [
                'class_name' => 'eldestilador',
                'alt_name' => 'eldestilador_blanco',
                'url' => 'https://www.tequilamatchmaker.com/tequilas/2428-el-destilador-blanco',
                'image' => 'eldestilador_blanco.jpg',
                'aging' => 'Blanco',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'ニュートン・エ・イホス蒸留所',
                'contents_nom' => '1173',
                'contents_area' => 'ソナ・セントロ地方/サポパン地区',
                'contents_info' => '',
                'contents_review_flavor' => '爽やかに鼻に抜ける香り',
                'contents_review_top' => '辛い口当たり',
                'contents_review_after' => '',
            ],
            // Tres Alegres Compadres
            [
                'class_name' => 'tresalegrescompadres',
                'alt_name' => '',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=6448',
                'image' => 'tresalegrescompadres_blanco.jpg',
                'aging' => 'Blanco',
                'contents_alc' => '38%',
                'contents_dest' => 'ラ・コフラディア蒸留所',
                'contents_nom' => '1137',
                'contents_area' => 'バジェス地方/テキーラ地区',
                'contents_info' => '',
                'contents_review_flavor' => '熟成されたような香り',
                'contents_review_top' => '癖の少ない飲みやすさ',
                'contents_review_after' => '',
            ],
            // Hijosdevilla
            [
                'class_name' => 'hijosdevilla',
                'alt_name' => 'hijosdevilla_blanco',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=7475',
                'image' => 'hijosdevilla_blanco.jpg',
                'aging' => 'Blanco',
                'contents_alc' => '40%',
                'contents_dest' => 'リコーレス・ヴェラクルス蒸留所',
                'contents_nom' => '1433',
                'contents_area' => 'ロスアルトス地方/アトトニルコ地区',
                'contents_info' => '',
                'contents_review_flavor' => '強いアガベの草の香り',
                'contents_review_top' => '甘く角のない舌触り',
                'contents_review_after' => '',
            ],
            // Gran Centenario
            [
                'class_name' => 'grancentenario',
                'alt_name' => 'grancentenario_anejo',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=3150',
                'image' => 'grancentenario_anejo.jpg',
                'aging' => 'Anejo',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'エクセハシエンダ・ロス・カミチネス蒸留所',
                'contents_nom' => '1122',
                'contents_area' => 'ロスアルトス地方/ラ・ラハ地区',
                'contents_info' => '',
                'contents_review_flavor' => '華やかに口の中に広がるバニラの薫香',
                'contents_review_top' => 'まろやかな甘味',
                'contents_review_after' => '',
            ],
            // Chilecariente
            [
                'class_name' => 'chilecariente',
                'alt_name' => 'chilecariente_blanco',
                'url' => 'http://www.premium-tequila.jp/products/list.php?category_id=232',
                'image' => 'chilecariente_blanco.jpg',
                'aging' => 'Blanco',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'グルポ・テキレロ・デ・ロスアルトス蒸留所',
                'contents_nom' => '1548',
                'contents_area' => 'ロスアルトス地方/アランダス地区',
                'contents_info' => '',
                'contents_review_flavor' => 'アガベ草感残る芳香',
                'contents_review_top' => '甘味の抑えたスパイシーな口当たり',
                'contents_review_after' => 'まろやかな甘味',
            ],
            // Tres Magueyes
            [
                'class_name' => 'tresmagueyes',
                'alt_name' => 'tresmagueyes_blanco',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=3815',
                'image' => 'tresmagueyes_blanco.jpg',
                'aging' => 'Blanco',
                'contents_alc' => '38%',
                'contents_dest' => 'ドン・フリオ蒸留所',
                'contents_nom' => '1449',
                'contents_area' => 'ロスアルトス地方/アトトニルコ地区',
                'contents_info' => '',
                'contents_review_flavor' => 'アガベの爽やかな香り',
                'contents_review_top' => 'スッキリとした苦み',
                'contents_review_after' => '残るアルコール感',
            ],
            // Casino Azul
            [
                'class_name' => 'casinoazul',
                'alt_name' => 'casinoazul_silver',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=10109',
                'image' => 'casinoazul_silver.jpg',
                'aging' => 'Silver',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'トレス・ムヘレス蒸留所',
                'contents_nom' => '1466',
                'contents_area' => 'バジェス地方/アマティタン地区',
                'contents_info' => '',
                'contents_review_flavor' => '芳醇なアガベの香り',
                'contents_review_top' => 'ほのかなスパイスと甘み',
                'contents_review_after' => '',
            ],
            // El Padrino
            [
                'class_name' => 'elpadrino',
                'alt_name' => 'elpadrino_blanco',
                'url' => 'https://www.musashiya-net.co.jp/products/detail.php?product_id=7565',
                'image' => 'elpadrino_blanco.jpg',
                'aging' => 'Blanco',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'デル・バジェ・デ・テキーラ蒸留所',
                'contents_nom' => '1438',
                'contents_area' => 'バジェス地方/アマティタン地区',
                'contents_info' => '',
                'contents_review_flavor' => '柔らかにアガベが薫る',
                'contents_review_top' => 'さらりとした口当たりで飲みやすい',
                'contents_review_after' => '',
            ],
            // La Cofradia
            [
                'class_name' => 'lacofradia',
                'alt_name' => 'lacofradia_anejo',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=943',
                'image' => 'lacofradia_anejo.jpg',
                'aging' => 'Anejo',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'ラ・コフラディア蒸留所',
                'contents_nom' => '1137',
                'contents_area' => 'バジェス地方/テキーラ地区',
                'contents_info' => '12ヶ月樽熟成',
                'contents_review_flavor' => '樽の発酵感を感じる柔らかな香り',
                'contents_review_top' => 'カラメルのような甘み',
                'contents_review_after' => 'キレのある酸味 ',
            ],
            // Dona Celia
            [
                'class_name' => 'donacelia',
                'alt_name' => 'donacelia_reposado',
                'url' => 'https://www.premium-tequila.jp/products/detail.php?product_id=261',
                'image' => 'donacelia_reposado.jpg',
                'aging' => 'Reposado',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'デル・バジェ・デ・テキーラ蒸留所',
                'contents_nom' => '1438',
                'contents_area' => 'バジェス地方/テキーラ地区',
                'contents_info' => '',
                'contents_review_flavor' => '鼻に広がる芯のあるカカオの香り',
                'contents_review_top' => '甘みと微かな酸味のキレの共存',
                'contents_review_after' => '締まりのあるアルコール感',
            ],
            [
                'class_name' => 'donacelia',
                'alt_name' => 'donacelia_anejo',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=262',
                'image' => 'donacelia_anejo.jpg',
                'aging' => 'Anejo',
                'contents_alc' => '40%/100%AGAVE',
                'contents_dest' => 'デル・バジェ・デ・テキーラ蒸留所',
                'contents_nom' => '1438',
                'contents_area' => 'バジェス地方/テキーラ地区',
                'contents_info' => '1～3年アメリカンオーク樽熟成',
                'contents_review_flavor' => 'ビターカカオのような強い香り',
                'contents_review_top' => 'すっきりとした酸味の口当たり',
                'contents_review_after' => 'はっきりとした甘みの後味',
            ],
            // Don Fernando
            [
                'class_name' => 'donfernando',
                'alt_name' => 'donfernando_anejo',
                'url' => 'http://www.premium-tequila.jp/products/detail.php?product_id=176',
                'image' => 'donfernando_anejo.jpg',
                'aging' => 'Anejo',
                'contents_alc' => '38%/100%AGAVE',
                'contents_dest' => 'バランカ・デ・アマティタン蒸留所',
                'contents_nom' => '1473',
                'contents_area' => 'バジェス地方/アマティタン地区',
                'contents_info' => '24ヶ月フレンチオーク樽熟成',
                'contents_review_flavor' => '樽の発酵香とほんのり甘い香り',
                'contents_review_top' => 'カカオのような甘い口当たり',
                'contents_review_after' => '酸味がするっと飲みやすい',
            ],
        ];

        // データを初期化
        DB::table('syouhin')->truncate();

        // テーブルにデータを挿入
        foreach ($syouhin as $each_syouhin) {
            DB::table('syouhin')->insert([
                'class_name' => $each_syouhin['class_name'],
                'alt_name' => $each_syouhin['alt_name'],
                'url' => $each_syouhin['url'],
                'image' => $each_syouhin['image'],
                'aging' => $each_syouhin['aging'],
                'contents_alc' => $each_syouhin['contents_alc'],
                'contents_dest' => $each_syouhin['contents_dest'],
                'contents_nom' => $each_syouhin['contents_nom'],
                'contents_area' => $each_syouhin['contents_area'],
                'contents_info' => $each_syouhin['contents_info'],
                'contents_review_flavor' => $each_syouhin['contents_review_flavor'],
                'contents_review_top' => $each_syouhin['contents_review_top'],
                'contents_review_after' => $each_syouhin['contents_review_after'],
            ]);
        }

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('syouhin');
    }
}
