<?php
/*
|--------------------------------------------------------------------------
| input項目の設定
|--------------------------------------------------------------------------
*/
return [
    'title' => [
        '項目名',
        '入力項目',
        '入力ガイド',
        'サンプル',
    ],
    'contents' => [
        'brand_id' => [
            'title' => 'ブランドID',
            'type' => 'hidden',
            'hidden' => true,
            'description' => 'ブランドを識別するためのID',
            'sample' => 'sauza',
        ],
        'brand_name' => [
            'title' => 'ブランド',
            'type' => 'select',
            'hidden' => false,
            'description' => '登録対象のブランドを選択してください<br>※選択肢にない場合はブランドマスタ登録して下さい',
            'sample' => 'SAUZA',
        ],
        'syouhin_id' => [
            'title' => '商品ID',
            'type' => 'hidden',
            'hidden' => true,
            'description' => 'ブランドID＋_＋熟成度ID',
            'sample' => 'sauza_frute_silver',
        ],
        'syouhin_url' => [
            'title' => '商品リンク',
            'type' => 'text',
            'hidden' => false,
            'description' => '外部リンクをクリックした際の商品購入ページなどの参照リンクを入力して下さい',
            'sample' => 'http://www.tequipedia.com',
        ],
        'image' => [
            'title' => '画像ファイル',
            'type' => 'file',
            'hidden' => false,
            'description' => '表示させたい画像（正方形サイズ）をアップロードして下さい<br>※推奨：JPEG(300 x 300)',
            'sample' => '-',
        ],
        'aging_sort' => [
            'title' => '熟成度分類',
            'type' => 'select',
            'hidden' => false,
            'description' => 'ブランコ・レポサドなどの熟成度の分類を選択してください<br>※シルバー・プラタなどはブランコを選択して下さい',
            'sample' => 'ブランコ',
        ],
        'aging_id' => [
            'title' => '熟成度ID',
            'type' => 'text',
            'hidden' => false,
            'description' => '登録商品を識別する熟成度IDを入力してください<br>※半角小文字英数字＋下線（_）',
            'sample' => 'frute_silver',
        ],
        'aging_name' => [
            'title' => '熟成度<br>（商品名）',
            'type' => 'text',
            'hidden' => false,
            'description' => 'シルバー・レポサドなど、登録商品の熟成度名（商品名）を入力してください<br>※半角英数字＋半角スペース（ ）',
            'sample' => 'Frute Silver',
        ],
        'alc_degree' => [
            'title' => '度数',
            'type' => 'select',
            'hidden' => false,
            'description' => '登録商品のアルコール度数を選択して下さい',
            'sample' => '40%',
        ],
        'mix_degree' => [
            'title' => '混合度',
            'type' => 'select',
            'hidden' => false,
            'description' => '登録商品のアガベ混合度数を選択して下さい<br>※アガベ使用率100%未満のものは「ミクスト」<br>※糖蜜・香料など1%以上添加の場合「リキュール」',
            'sample' => 'ミクスト',
        ],
        'min_price' => [
            'title' => '参考価格',
            'type' => 'text',
            'hidden' => false,
            'description' => '販売される価格の相場を入力してください<br>※十の位以下は四捨五入して下さい<br>※¥マークやカンマは不要です',
            'sample' => '1500',
        ],
        'dest_name_kana' => [
            'title' => '蒸留所',
            'type' => 'select',
            'hidden' => false,
            'description' => '生産された蒸留所名を選択して下さい<br>※選択肢にない場合は蒸留所マスタ登録して下さい',
            'sample' => 'サウザ蒸留所',
        ],
        'dest_nom' => [
            'title' => 'NOM',
            'type' => 'hidden',
            'hidden' => true,
            'description' => '生産された蒸留所番号',
            'sample' => '1102',
        ],
        'local_id' => [
            'title' => '生産地方ID',
            'type' => 'hidden',
            'hidden' => true,
            'description' => '生産地方の識別ID',
            'sample' => 'valles',
        ],
        'local_name_kana' => [
            'title' => '生産地方',
            'type' => 'select',
            'hidden' => false,
            'description' => '生産された州・地方名を選択して下さい<br>※選択肢にない場合は生産地方マスタ登録して下さい',
            'sample' => 'ハリスコ州バジェス地方',
        ],
        'area_id' => [
            'title' => '生産エリアID',
            'type' => 'hidden',
            'hidden' => true,
            'description' => '生産エリアの識別ID',
            'sample' => 'tequila',
        ],
        'area_name_kana' => [
            'title' => '生産エリア',
            'type' => 'select',
            'hidden' => false,
            'description' => '生産されたエリア名を選択して下さい<br>※特にない場合は「（空白）」を選択して下さい<br>※選択肢にない場合は生産地区マスタ登録して下さい',
            'sample' => 'テキーラ地区',
        ],
        'information' => [
            'title' => '情報',
            'type' => 'textarea',
            'hidden' => false,
            'description' => '商品に関する生産方法などのプチ情報を入力して下さい',
            'sample' => 'フレンチオーク樽で3年熟成',
        ],
        'review_flavor' => [
            'title' => 'レビュー：香り',
            'type' => 'textarea',
            'hidden' => false,
            'description' => '香りに関するレビューを入力して下さい',
            'sample' => '華やかなバニラのような香り',
        ],
        'review_top' => [
            'title' => 'レビュー：味',
            'type' => 'textarea',
            'hidden' => false,
            'description' => '味に関するレビューを入力して下さい',
            'sample' => 'なめらかな舌触りと甘み',
        ],
        'review_after' => [
            'title' => 'レビュー：余韻',
            'type' => 'textarea',
            'hidden' => false,
            'description' => '口の中に残る余韻に関するレビューを入力して下さい',
            'sample' => '舌に残る甘味と爽やかな後味',
        ],
    ],
];
